quarkus.http.port=8080

## simulator properties
version=1.0.0
instanceId=b0bc3081
replicaId=001

## URLs of external services
simulationServiceUrl=https://my.domain.net/my-simulator
callback.url.base=http://0.0.0.0:9090/simulation/v1/report
websocket.url.base=ws://0.0.0.0:9090/service-registration

## Oauth access token used in communication with external services
access-token=eyJz93ak4laUWw