quarkus.http.port=8080
version=0.5.0
simulationServiceUrl=https://my.domain.net/my-simulator
callback.url.base=http://localhost:9090/simulation/v1/report
websocket.url.base=ws://localhost:9090/service-registration