quarkus.http.port=8080

## simulator properties
version=1.0.0
instanceId=b0bc3081
replicaId=001

## URL the simulation service listens to.
simulationServiceUrl=https://0.0.0.0:8080/simulation/v1/

## URL of the test environment to send reports and metadata to.
callback.url.base=http://localhost:9090/simulation/v1/report
websocket.url.base=ws://localhost:9090/service-registration

## URLs of the mock test environment to send reports and metadata to on docker
# callback.url.base=http://iua-ru-mock:9090/simulation/v1/report
# websocket.url.base=ws://iua-ru-mock:9090/service-registration

## Oauth access token used in communication with external services
access-token=eyJz93ak4laUWw